#!/bin/bash

# Tool for building Qwin userspace for host kernel

CC="gcc"

sys=`uname`
if [ -e $sys ]; then rm -rf $sys;fi

mkdir $sys
for i in base64 cat cowsay echo grep ln head tail mkdir rm wc mknod pwd mv false true uname; do $CC $i.c -o `uname`/$i -std=gnu11;done
